### ISSUE TITLE
Add navigation through static FAQ categories

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#11]
Acceptance criteria:
- User can navigate through subcategories of FAQs
- User can jump back to parent category by clicking on "back"
- User can navigate through parent categories by clicking on breadcrumbs

**note**
- transition between categories should be prepared by design team
- ~we don't have API for this(related to login status)~

Design: https://marvelapp.com/7iihb90/screen/39265582

**Comment by MagdalenaAlmanova** [comment]
I found one thing. There was the` "Back"` button missing.
![screen shot 2018-04-26 at 21 20 39](https://user-images.githubusercontent.com/37298895/39327484-6fdc1550-4998-11e8-8850-c18acf760a70.png)

_Note: The text of some subcategories was out of the box._
![screen shot 2018-04-26 at 21 22 00](https://user-images.githubusercontent.com/37298895/39327529-92d8947a-4998-11e8-9998-b80274cc9fc8.png)

Thanks,
Meggy

**Comment by MagdalenaAlmanova** [comment]
Two mistakes have been fixed, but I am not sure if correctly. In case the question is longer, shouldn't it continue on the next line?
**Demo v.**
![screen shot 2018-05-10 at 00 11 18](https://user-images.githubusercontent.com/37298895/39842465-c019cbae-53e6-11e8-95f9-017e1dae24cf.png)

**Prototype v.**
![screen shot 2018-05-10 at 00 12 30](https://user-images.githubusercontent.com/37298895/39842500-ddedb348-53e6-11e8-97ea-9a0ead28eeb2.png)

Thank you for your answer :)
M.

**Comment by MagdalenaAlmanova** [comment]
It was my mistake, I have forgotten to assign you, sorry.

I checked it again and the recognized mistake was repaired. I found also something else. The description of the question doesn't continue to the next line as in the zeplin 1b-2a-1. 
Demo v.
![screen shot 2018-05-15 at 21 08 12](https://user-images.githubusercontent.com/37298895/40078191-3ab206f0-5884-11e8-9187-eef3aa1c3a95.png)

Prototype v.
![screen shot 2018-05-15 at 21 03 22](https://user-images.githubusercontent.com/37298895/40078134-0dc26a04-5884-11e8-8b82-e226fd30e374.png)
 

Thanks :) @jalbertsr

**Comment by jalbertsr** [comment]
maybe @kantord can answer you better about why we used `...`, I think they talk about it [here](https://github.com/kiwicom/smart-faq/pull/125/files/890d54c07d414bb532d18f2a1b720d7f16a59af2#diff-3ef3f5f6537123e2b7483bff463e4c26) , if I'm not wrong we used it because the content of the perexes of the articles are not yet updated for our desings and are still in the old help center format.

**Comment by kantord** [comment]
Using ellipses (`...`s) is a simplification. The issue was that the cards were overflowing, and they were designed to have a fixed height. Which means, that if there is not enough vertical space then something has to be cut short. Ideally, it would only happen if both the perex and the header are long, since if only the title is long, it could break into two lines. It might be possible to implement that using flexbox and some hacks, but that might be an overkill.

I am not going into deep technical details here as it might not be necessary, but if you want to know just ask :-)

**Comment by jalbertsr** [comment]
what we should do @MRTNKCR ? 

keep using `...` until the format and length of the perexes are correct(content of the knowledge base is updated) so we don't have overflowing text or display the current content(might create overflowing text in some cards)
