### ISSUE TITLE
BUG: Hidden part of the breadcrumbs navigation

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#158]
For those articles deep in the category structure (or featuring a long title), part of the breadcrumbs navigation is hidden. We might use the same approach as on mobile (three dots in the middle of the string), but I'm not sure this is enough. I will discuss with Martin Jancik and update the ticket with a solution.

![snimek obrazovky 2018-05-11 v 10 15 53](https://user-images.githubusercontent.com/7661448/39915002-fb5a8bce-5506-11e8-9e1b-d1ae69c18cd1.png)

![snimek obrazovky 2018-05-11 v 10 21 22](https://user-images.githubusercontent.com/7661448/39915004-ff5bc738-5506-11e8-842f-0852deb94c2b.png)

**Comment by kantord** [comment]
I have a suggestion, although I have not tried it yet. So here it is:

We could keep using `text-overflow: ellipsis` but with a twist. Instead of trimming the entire breadcrumb to size, we would use flexbox or something else to ensure that the last and first element in the breadcrumb are fully displayed (or fully displayed if they fit in a certain pixel limit). Then, we would cut only the middle part with an ellipsis (...).

Also, we might save a few pixels if:
- we replace 'Home' and 'Search' with small :house: and :mag: icons
- we remove the last part of the breadcrumb ('Article' or the category title) and instead display it on a separate line as a header (as it is already done with the article details)

**Comment by mjancik** [comment]
Hi. There should always be only `article` in the last part of the breadcrumbs. There is no need to duplicate the information user sees right underneath (article name). 
![2-1a-3 help article](https://user-images.githubusercontent.com/37365838/41522693-782d612e-72d7-11e8-8bdf-863069103150.png)

Also the same (...) behaviour applies as on mobile. if it really is too long, meaning that first, last and the one before last have priority and have to be shown. All the in the middle are hidden.
