### ISSUE TITLE
Refactor CSS in ContentHeader

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#179]
As you can see, there's a lot of duplication here. Some parts of the implementation are copied entirely, and some parts implement essentially the same thing, but in a different way. This might also due to differences in the component structure.

```
  div.loggedOut {
    display: flex;
    justify-content: space-between;
    padding: 15px 122px 15px 40px;
  }
  div.header {
    display: flex;
    align-items: center;
    height: 64px;
  }
  div.ContentHeader {
    width: 100%;
    border-bottom: 1px solid #e8edf1;
    background-color: #ffffff;
  }
  div.FAQ {
    width: 480px;
  }
  div.faqLink {
    margin-left: 182px;
    line-height: 1.4;
  }
```

```
  div.helpHeader {
    font-size: 28px;
    font-weight: bold;
    color: #171b1e;
  }
  div.loggedIn {
    display: flex;
    justify-content: space-between;
    padding: 15px 122px 15px 40px;
  }
  div.links {
    display: flex;
    align-items: center;
  }
  div.faqLink {
    display: flex;
    margin-right: 58px;
  }
  a.open-icon {
    margin-left: 12px;
  }
  @media only screen and (min-device-width: 320px) and (max-device-width: 480px) {
    div.loggedIn {
      padding: 15px;
    }
    div.helpHeader {
      width: 100%;
      text-align: center;
    }
  }
```

**Comment by git-toni** [comment]
Note you are pasting code from your branch, not master :slightly_smiling_face: 

Agree there's plenty of refactor potential here to minimize duplication. However in this case (and since I'm the culprit of this duplication :D ) I'll say it was mainly due to being able to separate the render logic of logged-in case versus logged-out case and at the same time play well with styled-jsx.

Some suggestions to refactor in case it helps:
- Try to replace some diff classnames with one eg. loggedIn + loggedOut ---> someClass. And extract that logic to the common component `ContentHeader`.
- Extract the responsive logic and concat it later to the common style.

**Comment by kantord** [comment]
I am assigning this to myself unless you have an objection :-)
