### ISSUE TITLE
Carrierlogos render components with repeated key

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#217]
Since we use Orbit's `CarrierLogo` component, and since that component is setting the `key` to `code` [here](https://github.com/kiwicom/orbit-components/blob/master/src/CarrierLogo/index.js#L45), it seems that in cases with multiple legs the key is repeated raising React warnings.

The solution is ideally to PR a refactor of the Orbit component, tho I'm raising it here to discuss what the best approach is based on our project's needs. I suggest to send a prop to `CarrierLogo` component called `renderKey` of the given carrier, and have `code` as the default.

![image](https://user-images.githubusercontent.com/2466887/40374987-a4efdc0c-5dea-11e8-8194-0ea0d797f5f5.png)

**Comment by kantord** [comment]
Why does CarrierLogo even need a key on its own?

**Comment by git-toni** [comment]
@kantord I don't understand your question. What do you mean? They key is not for `CarrierLogo` itself but for each of the `img` elements it renders as an array.

**Comment by kantord** [comment]
@git-toni I just checked out the source code for CarrierLogo and turns out I misunderstood how it works :-) A possible downside to passing down renderKey is that I think it'd be too much work to deal with this issue separately in each project/component where this orbit component is used. It might be fine to just use a random ID in the orbit component (uuid?) as key. Or we could use this format: `ASD-Anti Standard-Airlines-2` where 2 means it's the second occurrence of the same airline.

**Comment by jalbertsr** [comment]
well, all this will be resolved with this PR https://github.com/kiwicom/smart-faq/pull/230 since in the graphql resolver, carriers are filtered.

**Comment by git-toni** [comment]
I agree with @jalbertsr, graphql is now providing us with *unique* carriers based on attr `code` which is the one that created this issue.
