### ISSUE TITLE
Create Sign In page

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#25]
*Note: does not require the actual login logic yet, only meant to build the screen flow*
According to zeplin UI: https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5aa6b8e08c098575718bda8d

Criteria:
- [x] Match zeplin design.
- [x] Add tests.
- [x] Add storybook.
- [x] Add links for screen transitions.

**Comment by MRTNKCR** [comment]
ready for @MagdalenaAlmanova to test it? @git-toni If so, assign her to the issue please. Thank you :-)

**Comment by MagdalenaAlmanova** [comment]
**Bug 1:** 
Missing space between the end of the "your@email.com" button and start of the “Get Help" button.
**_Demo version:_**
![screen shot 2018-03-21 at 22 11 00](https://user-images.githubusercontent.com/37298895/37738150-6300e31e-2d56-11e8-835f-8c163f546882.png)
**_Prototype :_**
![screen shot 2018-03-21 at 22 23 48](https://user-images.githubusercontent.com/37298895/37738233-9c30ba56-2d56-11e8-9293-a59e7ba6ce5e.png)

**Bug 2:** 
In Mozilla Firefox, the text in text-box "your@example.com" is not aligned at the centre of the text-box, compared to other browser and prototype versions. Mozilla Firefox v. 59.0.1 
![screen shot 2018-03-21 at 22 08 41](https://user-images.githubusercontent.com/37298895/37738160-688c3a36-2d56-11e8-8b9b-aaae7632cc5f.png)

_Notes:_
The font and picture in demo is always bigger compared to the prototype version, I have already asked about this in the previous issues. 

I think that button "kiwi.com account” is at the very bottom of the page in the Opera.
![screen shot 2018-03-21 at 22 37 57](https://user-images.githubusercontent.com/37298895/37738862-a0019ed2-2d58-11e8-80fc-40f89b7b303b.png)

 I am not sure, whether the link should be used instead of the button,  like on the prototype page. Am I right?  
![screen shot 2018-03-21 at 22 17 43](https://user-images.githubusercontent.com/37298895/37738185-79454d72-2d56-11e8-8e7a-ee4b600ec517.png)

@git-toni @jalbertsr 

Thank you

**Comment by jalbertsr** [comment]
Yes, UX changed the design after I finished it, but before you tested it, I will redo according to the updated design.

**Comment by MagdalenaAlmanova** [comment]
**It is alright 💯**  for me.
