### ISSUE TITLE
Update layout for tablets

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#502]
Tablet in landscape mode should display normal desktop version, just with tighter FAQ column: https://zpl.io/a74G9qp

Tablet in portrait will be similar to mobile in landscape - intro & login screens centered  https://zpl.io/begmngq but images and texts like "We're here for you. First, let's narrow down your request." will be shown

**Comment by MagdalenaAlmanova** [comment]
Hmm...there is some mistake. On iPad Pro it shows me odd version of Smart Faq. 
![img_0199](https://user-images.githubusercontent.com/37298895/42595053-4abc605a-8551-11e8-9cdf-db9735a48b44.jpeg)
![img_0198](https://user-images.githubusercontent.com/37298895/42595061-50d959d4-8551-11e8-867e-76db9b4a2b16.jpeg)
![img_0200](https://user-images.githubusercontent.com/37298895/42595238-efeed800-8551-11e8-9056-8576a6f01576.jpeg)

I tried it on Safari, Chrome and Opera mini last versions. Can it be because I tested this on iPad Pro, or? @kantord @jalbertsr

**Comment by jalbertsr** [comment]
Breakpoint are not working properly, see strange error on issues https://github.com/kiwicom/smart-faq/issues/538, https://github.com/kiwicom/smart-faq/issues/512

**Comment by MagdalenaAlmanova** [comment]
👍
