### ISSUE TITLE
Mobile: Fetch list of FAQs based on status of the booking

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#512]
Fetch list of FAQ based on the status of the booking displayed on SingleBookingPage on mobile - BEFORE_BOOKING - for not logged in user
BOOKING - for user with booking with departure in more than 48 hours
BOOKING_URGENT - for a user with booking with departure in less than 48 hours and before final arrival
PAST_BOOKING - for a user with past booking

This issue is almost identical to https://github.com/kiwicom/smart-faq/issues/324, we just need to add mobile support.

**Comment by MagdalenaAlmanova** [comment]
It doesn't work, see on screenshots. 
![img_9632](https://user-images.githubusercontent.com/37298895/42388268-3e19b434-8145-11e8-8b39-a5ac7510f22e.PNG)
![img_9631](https://user-images.githubusercontent.com/37298895/42388271-418f2072-8145-11e8-86ae-a6f7332b367b.PNG)

Tested at iPhone 6S, Safari, and mini Opera both last versions.

**Comment by MagdalenaAlmanova** [comment]
I cannot test it now, because on iPhone  Smart Faq doesn't work correctly. When  I signed in it shows me this: 
![img_9781](https://user-images.githubusercontent.com/37298895/42655156-71cc2854-861b-11e8-9a69-59bf0d8e18ee.PNG)

I couldn't choose between trips. I tried on iPhone 6S on Safari, Opera Mini, and Chrome last versions.
 

@kantord

**Comment by jalbertsr** [comment]
This problem is related to issue: https://github.com/kiwicom/smart-faq/issues/502, once solved try to retest again. Thanks.

**Comment by MagdalenaAlmanova** [comment]
I am sorry, but I don't have good news.

In Safari and Chrome, I cannot choose between trips. It returned me to on the first page.
![img_9837](https://user-images.githubusercontent.com/37298895/42779582-251fecd8-8941-11e8-9a2c-e96ef468457b.PNG)
![img_9838](https://user-images.githubusercontent.com/37298895/42779589-27b116de-8941-11e8-8794-cf9d41b4fc65.PNG)

And in Opera Mini, besides the mentioned error, there is a bug with login. 
![img_9839](https://user-images.githubusercontent.com/37298895/42779882-fc7b46aa-8941-11e8-8c1e-9decbce2667f.PNG)

For better understanding, I will send you videos on slack in DM. @jalbertsr @kantord

**Comment by jalbertsr** [comment]
This is caused because of the huge amount of bookings test account have(+80 bookings) which isn't what our average client has, I will send you credentials for the react native test account so you can test with a more realistic account (8 ~ 12 bookings), I will open another issue to load in a different way all these bookings so we don't crash the mobile browser.

**Comment by MagdalenaAlmanova** [comment]
Thanks for the new test account, I tried it again and It works :) Please don't forget for opera mini bug with login page :) It is still persistent.
