### ISSUE TITLE
Add cypress tests that will verify social login

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#603]
Add Cypress test on FE repo to verify that it's possible to log in with social account AND user is then redirected to page with booking - automatically.

Related bug: #592

**Comment by jalbertsr** [comment]
Since visiting external sites is not a good practice, check [Cypress.io docs](https://docs.cypress.io/guides/references/best-practices.html#Visiting-external-sites).
I followed the recommendation of one the maintainers see -> https://github.com/cypress-io/cypress/issues/1380#issuecomment-368663427
I was trying to follow these examples from [official cypress repo](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__single-sign-on/cypress/integration/logging-in-single-sign-on-spec.js), but in kiwi we call our own backend and is this backend the one who makes the final call to get the redirect link. Maybe this is why there are no cypress social login test in kiwi frontend either, only kiwi login test.

Opinions, recomendations?
