### ISSUE TITLE
Add "was this helpful" feedback buttons below FAQ article

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#68]
<img width="251" alt="screen shot 2018-04-09 at 16 56 58" src="https://user-images.githubusercontent.com/2174629/38508554-61315d96-3c17-11e8-8a54-6214d6cfc934.png">

**Needs clarification**
- What should happen after clicking on "yes"/ "no"
- where do we store data? (there is API in https://gitlab.skypicker.com/django-team/knowledgebase#article-voting - should we used this?)

**Comment by git-toni** [comment]
I'll start by wrapping the article voting API with GraphQL mutations :)

**Comment by git-toni** [comment]
PR for graphql is here: https://github.com/kiwicom/graphql/pull/85

**Comment by git-toni** [comment]
@MRTNKCR Are the screens for the frontend part ready? Eg. should we implement this as the image @jaroslav-kubicek pasted in this description?

**Comment by MRTNKCR** [comment]
No, I discussed with Martin Jancik today and he's still not sure about the final version of this. Sorry about that - I'll push him to deliver the design asap.

**Comment by git-toni** [comment]
Thanks! Not crazy urgent either :)

**Comment by MRTNKCR** [comment]
The design has been uploaded to zeplin: rather than yes or no, we suggest the pap to contact our CS and ask him for a feedback at the same time. Here is Zeplin: https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5ade0df24c3924b93d8e83a3

![snimek obrazovky 2018-04-24 v 9 46 19](https://user-images.githubusercontent.com/7661448/39173242-7335933e-47a4-11e8-9b0d-c99c9d9271d6.png)
![snimek obrazovky 2018-04-24 v 9 46 30](https://user-images.githubusercontent.com/7661448/39173243-7356d300-47a4-11e8-9b77-3d43f9bfa8ba.png)
![snimek obrazovky 2018-04-24 v 9 46 44](https://user-images.githubusercontent.com/7661448/39173244-7372adaa-47a4-11e8-99d1-0749c2175b08.png)

**Comment by git-toni** [comment]
Interesting, thanks for pointing it out. In that case we would need backend to implement that feature? Or is it the same as article commenting here? https://gitlab.skypicker.com/django-team/knowledgebase#article-comment

**Comment by jalbertsr** [comment]
"ask us" button not centred.

it works on: https://kiwicom.github.io/smart-faq/

dosent work on: https://introduce-smart-faq.fe.staging.kiwi.com/en/

![screenshot](https://i.gyazo.com/506f9163a134c33e18125f59474ebaae.png)

ps: this issue was not in the github board nor in the 'todo' or 'in progress'

**Comment by jalbertsr** [comment]
close because I reopened but it was duplicated of https://github.com/kiwicom/smart-faq/issues/183

**Comment by MagdalenaAlmanova** [comment]
Only one thing, the text "Your feedback helps us improve." and "Thanks again, we appreciate your insight." should be bold. 
Demo v.
![screen shot 2018-05-28 at 22 33 52](https://user-images.githubusercontent.com/37298895/40628935-5574495a-62c8-11e8-80cd-316761fa6659.png)
![screen shot 2018-05-28 at 22 34 44](https://user-images.githubusercontent.com/37298895/40628938-5e445570-62c8-11e8-9416-e9c37d075150.png)
Prototy v. 
![screen shot 2018-05-28 at 22 34 04](https://user-images.githubusercontent.com/37298895/40628943-65940ed8-62c8-11e8-8a62-462c4dcb2de8.png)
![screen shot 2018-05-28 at 22 34 33](https://user-images.githubusercontent.com/37298895/40628951-6a05c330-62c8-11e8-8328-0b333b36b8af.png)

Thanks

**Comment by MagdalenaAlmanova** [comment]
Ok.  Should not the text "go to contact page" also be bold?
