### ISSUE TITLE
Update Boarding passes to show info that airport checkin will be needed

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#689]
<img width="544" alt="screenshot 2018-08-27 10 10 21" src="https://user-images.githubusercontent.com/2174629/44648469-732f1000-a9e1-11e8-85ef-64782b9789a4.png">

Zeplin: https://zpl.io/aN09rwe

step I.
Add new GraphQL enum field `availabilityStatus` for `BoardingPass` with these values - `AVAILABLE`, `IN_FUTURE`, `AT_AIRPORT`, `OTHER`.

- AVAILABLE - file is available for download
- IN_FUTURE - file is not available, but date is known
- AT_AIRPORT - date is equal to `null`
- OTHER - all other cases

step II.

- show blue badge as in design for `AT_AIRPORT`

**Comment by kantord** [comment]
Question: is this information found in MMB backend? How do you find it? Just to make sure that it's not too difficult. Otherwise I'd create another issue for finding that out.

**Comment by Radek-Palisa** [comment]
I also have question: can it happen that the value of `availableAt` is a day in the past? and if so in what scenario this could occur? I made the logic of this new `availabilityStatus` enum field in a way that if `availabilityAt` is a past day, then it will return status `OTHER`.

**Comment by jalbertsr** [comment]
what happens with this design? 
![screenshot](https://i.gyazo.com/9a35f5620f71a661fae82e3c8e2d7f05.png)

Do we have enough information in backend to distinguish between these two cases?

**Comment by kantord** [comment]
I'd say looking that up should be a separate issue

**Comment by jalbertsr** [comment]
> I'd say looking that up should be a separate issue

yes, true, I was just raising the question.

**Comment by jalbertsr** [comment]
closed by https://github.com/kiwicom/smart-faq/pull/709

**Comment by MagdalenaAlmanova** [comment]
I just found two minor things. The first one is about the title "Your boarding passes". I think that it should be better centralized because it doesn't look good. 
Prototype. 
![screen shot 2018-09-06 at 20 53 10](https://user-images.githubusercontent.com/37298895/45179466-e540f980-b218-11e8-8826-59601cca5808.png)
Demo v.
![screen shot 2018-09-06 at 20 53 01](https://user-images.githubusercontent.com/37298895/45179467-e7a35380-b218-11e8-8947-014343f5189b.png)

The second minor thing is about the missing dot in the sentence "You will have to check-in for free at the airport." 
Prototype v. 
![screen shot 2018-09-06 at 20 52 51](https://user-images.githubusercontent.com/37298895/45179616-508acb80-b219-11e8-87d6-5d7ef03258ec.png)

Demo v.
![screen shot 2018-09-06 at 20 52 39](https://user-images.githubusercontent.com/37298895/45179682-7ca64c80-b219-11e8-9e20-356ecc706878.png)

Thank you :)

**Comment by jalbertsr** [comment]
@MagdalenaAlmanova check it again pls
